### ISSUE TITLE
Desert has no exit

### ISSUE THREAD

**Issue by DuncanFairley** [DuncanFairley/TWC#10]
In order to leave the Desert area you have to die to the Eyeballs which most people use in order to gain levels as well as money (Dying of course takes away half of your gold/exp). Suggestion for change is to add a proper way to exit the desert. Also consider redoing the entrance as well per suggestion via Justin, it is very weird entering the desert and could use some TLC (in terms of winding up on the bottom lefthand corner of a map with only one way to go, its not like you enter the area)

**Comment by ZachieBlade** [comment]
This can be closed too I believe
