### ISSUE TITLE
move_chat_logs

### ISSUE THREAD

**Issue by DuncanFairley** [DuncanFairley/TWC#204]
Our bash script for moving chat logs at the end of each day doesn't support making a new folder for a new year. Fix it!

```bash
#!/bin/bash
if [ ! -d /ssd/TWC/Logs/chatlogs/$(date +%y/%m) ];
then
#The month's folder doesn't exist, create it
mkdir /ssd/TWC/Logs/chatlogs/$(date +%y/%m);
fi
#Move current log into folder
mv /ssd/TWC/Logs/chatlog.html /ssd/TWC/Logs/chatlogs/$(date +%y/%m/%d).html

**Comment by DuncanFairley** [comment]
P.S. this is a TODO for you people - not me.

It's in BASH - a few minutes of googling should allow to you do it.

**Comment by Rotem12** [comment]
I'm a little confused, why would this script fail when year changes? It does include %y so if the year changes, it'll make a new folder from 14/12 to 15/01

Or do you want to another layer of folders where it's year folder\month folder\days

**Comment by DuncanFairley** [comment]
Because that mkdir will only make the m folder if the y folder exists.
I imagine that mkdir would have a parameter that would force create folders
if there's multiple levels.

**Comment by Rotem12** [comment]
Yea... all you need is to add -p

```bash
#!/bin/bash
if [ ! -d /ssd/TWC/Logs/chatlogs/$(date +%y/%m) ];
then
#The month's folder doesn't exist, create it
mkdir -p /ssd/TWC/Logs/chatlogs/$(date +%y/%m);
fi
#Move current log into folder
mv /ssd/TWC/Logs/chatlog.html /ssd/TWC/Logs/chatlogs/$(date +%y/%m/%d).html

**Comment by DuncanFairley** [comment]
Oh I totally forgot that you have shell access now... I think it might be in /home? or /root? It's called move_chat_logs.sh or something. Let me know if you can't find it.

**Comment by Rotem12** [comment]
Changed, I don't know whether I broke it or not though.
