### ISSUE TITLE
Add event information to Stats

### ISSUE THREAD

**Issue by Rotem12** [DuncanFairley/TWC#223]
When an event start it should be added to ongoing events list later displayed at stats.
If there is 1 or more events going when a player logs in, it should inform the player how many events going on and refer him to Stats tab.

**Comment by GameMaster85** [comment]
I've setup a list that is given the type of the event that is, or are, currently running. They are also removed when the event is over. This list is then appended to the statpanel, and can easily be edited to show a description or even current objectives. Right now, it currently shows the names of the events that are on-going. I don't want to merge request this one yet until the other one is already merged, so speak to me when you can about it.

**Comment by Rotem12** [comment]
I think that adding more details to it doesn't fit the current layout of random events, sure we can add some desc var but I don't really want to add too much details in Stats bar or do any drastic changes.

On the long run I'd also want to get rid of stats in favour of more modern skin layout, for now what we have will do.
