### ISSUE TITLE
Clan Add

### ISSUE THREAD

**Issue by Juxnist** [DuncanFairley/TWC#269]
That player does not exist. Contact Murrawhip with error code ba4fa if you believe this is in error.

1. Type a name into Clan Add. It can be any Clan or Non-Clan Member.
2. Hit Hire.
3. Get Error.

Type name/key of person you'd like to invite to the Death Eaters <-- yet it says you can use name

**Comment by Rotem12** [comment]
While clan hire is handy we'll most likely be ditching clanadmin.php
