### ISSUE TITLE
Event Logs

### ISSUE THREAD

**Issue by Juxnist** [DuncanFairley/TWC#270]
The Event Logs web page will make a seperate log for you if you happen to host an event after changing your name. It should just add it to your original log if the key is the same.

**Comment by Rotem12** [comment]
The event log mysql table has 3 columns, name, timestamp and message. The name column is the name + key. The only way I see to fix without touching the mysql is to remove names from it which makes this more uncomfortable.

I think this is too minor for me to care, it's usable, definitely remains readable after people rename.

**Comment by ZachieBlade** [comment]
Unless you switched the way the logs work? If you put key first and then sorted by name it'd still have it under the same heading.

**Comment by Rotem12** [comment]
And I'm telling you, that name and key are not two different fields but the same field, one field, unseperatable.

It's not Banana and Rotem12, it's one unique string "Banana (Rotem12)". Changing even the space in between will create a completely new unique string.
