### ISSUE TITLE
Convert suitable spells to projectiles

### ISSUE THREAD

**Issue by Rotem12** [DuncanFairley/TWC#338]
I'd rather have spells with projectiles and not grey pop ups, now it's something anyone could do by following flippendo or transfiguration example.

If at a later time we'd have a better method then we'll switch to it.

For bindings or unfair spells to the extreme, please cut down the duration of the effect, even 2-3 seconds for a binding spell will make a world difference and if it's a short period of time and a projectile it's most definitely something people would use in duels without shouting it's cheap

**Comment by Groudonmaster** [comment]
I think incarcerous could be changed into a fast moving rope like projectile. But if this happens I wouldn't feel comfortable lowering it beyond maybe a second or two.

**Comment by Juxnist** [comment]
Incarcerous was to be changed into a spell with a slow effect instead of a complete bind. Can't recall if we ever got around to it.

**Comment by Rotem12** [comment]
Actually, I've already completed this entire thing.
