### ISSUE TITLE
View Player Log needs an Upgrade

### ISSUE THREAD

**Issue by Noxara** [DuncanFairley/TWC#341]
proc/sql_retrieve_plyr_log should grab the list of ckeys it needs to check for in tblWarnings before it even runs the inital query.

Side Notes : It's a bit difficult to pull up one players logs to see previous punishments when some try to escape with new accounts or alts that have clear history. So linking them together will make it easy to show us any punishments that were recent or any punishments in general.

**Comment by DuncanFairley** [comment]
Change the player log list view to have a column for an associated ckey. Grab the ckeys associated with the IP of the ckey from tblPlayers then (ckey1,ckey2) list against that for the final query. Just throw the ckey in its own column for the result.

**Comment by Rotem12** [comment]
If this is optional then I have no problems with it. If I can allow admins to have this feature where untrusted GMs are denied then there's 0 cons.
