### ISSUE TITLE
Spell Slot Usage Bug

### ISSUE THREAD

**Issue by Pie314** [DuncanFairley/TWC#354]
While I was using spells to drag into slots, I've noticed something was wrong when I dragged out the spell to remove it. It turns out even if you removed it, and press that certain key you pressed you'll still use the same spell you have placed previously. And you can tell by dragging a "blank slot" out showing that spell's icon. (I can't get a screenshot pic for this.) Also, no macros were involved in hindering the spell slots. As you can see the spell doesn't remove its spell from the slot entirely(From the pic below). It could mess up someone's battle style or something if it was placed that was supposed to be gone.
![spslotz](https://cloud.githubusercontent.com/assets/13006438/8578476/0c64c702-257d-11e5-9006-b72a733138b3.jpg)

**Comment by Rotem12** [comment]
This does not reproduce.
