### ISSUE TITLE
Make a new icon for monster book of monsters and check if comc book is the same

### ISSUE THREAD

**Issue by Noxara** [DuncanFairley/TWC#356]
Both icons are extremely old and comc book reverts to blank book icon.

**Comment by Juxnist** [comment]
Both books use the same new book icon with a blank brown cover. Simply cause I couldn't decide what to put on the cover. Nothing is old about them. You guys crazy and need glasses.

**Comment by Rotem12** [comment]
Please make new icons for them, this issue will remain open as a reminder.
