### ISSUE TITLE
Possible Map Error

### ISSUE THREAD

**Issue by Pie314** [DuncanFairley/TWC#358]
This corner of the stairs in front of Hogwarts stairs being able to move diagonally even though there is a fence that should prevent the player from doing so.
![maperr](https://cloud.githubusercontent.com/assets/13006438/8648205/cacea6b0-292c-11e5-87b4-1623ee8e9540.jpg)

**Comment by Juxnist** [comment]
It's not only diagonal. You can move straight through it as well. It's simply missing a sideBlock turf.
