### ISSUE TITLE
Bank Gold Bug

### ISSUE THREAD

**Issue by Pie314** [DuncanFairley/TWC#372]
When I deposited 1 gold. The bank overall stays the same. Where as if I withdraw 2 and then deposit 1, it skips a number.
![bkgoldbug](https://cloud.githubusercontent.com/assets/13006438/8887608/ad9154d8-3257-11e5-9e06-e0f5944bd4a5.jpg)

**Comment by Rotem12** [comment]
BYOND's numbers are only accurate up to the around the 24th bit, which gives an effective accurate range of : 16777216 (negative to postive) only way to fix this bug is to revamp how gold works to result in smaller gold values.
