### ISSUE TITLE
When the hall becomes a kill zone event

### ISSUE THREAD

**Issue by chacuya34** [DuncanFairley/TWC#373]
When the hall becomes a kill zone event, the tiles are supposed to turn into kill zones and not safe zones.
Well, there are a few tiles that ARE safe zones.
I guess that's a bug, or someone forgot to ''safezone'' those tiles.
That's all.
![zones](https://cloud.githubusercontent.com/assets/13495240/8888957/106d914a-32c4-11e5-8a26-0a4378d376f3.png)

**Comment by ZachieBlade** [comment]
If you could, would you be able to screenshot which tiles remain safe zones? It's a very large area.

**Comment by chacuya34** [comment]
Done. Not sure if there are more.

**Comment by Juxnist** [comment]
Same as issue #374. Seems someone forgot to turn off click create.

**Comment by Pie314** [comment]
I was doing some searching during the killzone event. I've searched all of the bottom section. (Tube of Funs= Tiles that remained Safe zone.) 
![kzonebug](https://cloud.githubusercontent.com/assets/13006438/8919788/667d52b4-3490-11e5-8f9e-f218076d66e0.jpg)

**Comment by ZachieBlade** [comment]
This will be fixed on a reboot it's fine in the source
