### ISSUE TITLE
A wall block that isn't a ''night'' block

### ISSUE THREAD

**Issue by chacuya34** [DuncanFairley/TWC#374]
When night comes, all outside tiles are supposed to have a... ''night'' or ''dark'' tile.
And when day comes, those tiles get... bright? Don't know how to explain it.
Well, the bug is that there is a wall that doesn't turn into ''night'' tile when night comes.
Just go outside Hogwarts and you will see it.
That's all.
![datwall](https://cloud.githubusercontent.com/assets/13495240/8888984/0945ac62-32c5-11e5-91fd-8eac819d0568.png)

**Comment by Juxnist** [comment]
It's fine in the source. So someone must have changed the area at some point.
