### ISSUE TITLE
Acromantula Issue

### ISSUE THREAD

**Issue by Pie314** [DuncanFairley/TWC#388]
When you run towards the end of the wall, sometimes the Acromantulas go over the walls on the right side of the school and goes straight up to you.
![spiderz](https://cloud.githubusercontent.com/assets/13006438/10085556/e22a7106-62d7-11e5-9b6a-7a06a6dba74a.jpg)

**Comment by Rotem12** [comment]
Direct result of people abusing herbs, intended behavior as long as they don't get stuck there.
