### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by LuckySara** [DuncanFairley/TWC#405]
Links go purple even when not clicking on them. It also seems that without clicking on them when I came back onto the game, they were purple. As if I had clicked on them. Even if you click on one thing every single link gets pulled as if you touched it.

**Comment by Rotem12** [comment]
I can't reproduce this on my browser, what links are you referring to? The only one I saw that goes purple is forum link, PMs, OOC and the like retain their color never go purple.

**Comment by LuckySara** [comment]
Links like..Version number, Forums link, and Daily Prophet is just a few. Especially when I just logged in, they're purple. I never clicked on them when I logged in just now: http://puu.sh/lXXcl/ffe37cfadc.jpg

**Comment by Rotem12** [comment]
This isn't really a TWC issue, neither can I reproduce it.
