### ISSUE TITLE
An Edit/Pet issue?

### ISSUE THREAD

**Issue by LuckySara** [DuncanFairley/TWC#535]
So I accidently Mass-edited coloring my pet when coloring floors. I would edit it to fix it, causing it as a temporary fix. It would go back to the mass-edit color when I re-equip it.

It seems the coloring pet potion and then de-coloring pet potion is more of a permanent fix than if you edited the pet to fix it. I'm not sure if that's what it was meant to do, but it is odd to me that an Edit would be a temporary thing.

**Comment by Rotem12** [comment]
The pet object does not contain your pet item's true color, the real color comes from the item when you equip it. The pet object is temporary and thus any edits to it are.
